spring:
  datasource:
    url: jdbc:h2:mem:shareit_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: postgres
    password: 123456
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
