server:
  port: 8080

spring:
  application.name: shareit
  main.banner-mode: OFF
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
  datasource:
    username: "postgres"
    password: "123456"
    url: jdbc:postgresql://localhost:5432/shareit
    driver-class-name: "org.postgresql.Driver"

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG